// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UtilityManagement.Data;

#nullable disable

namespace UtilityManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260716063550_AddCompanyToUser")]
    partial class AddCompanyToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBoilerReadingInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<double?>("ChemicalTk")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CHEMICAL_TK");

                    b.Property<double?>("CngConM")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CNG_CON_M");

                    b.Property<double?>("CngMHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CNG_M_HR");

                    b.Property<double?>("CngRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CNG_RH");

                    b.Property<double?>("CngTkM")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CNG_TK_M");

                    b.Property<double?>("DslConLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DSL_CON_LTR");

                    b.Property<double?>("DslLtrHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DSL_LTR_HR");

                    b.Property<double?>("DslRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DSL_RH");

                    b.Property<double?>("DslTkLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DSL_TK_LTR");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("Kwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("KWH");

                    b.Property<double?>("LpgConKg")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LPG_CON_KG");

                    b.Property<double?>("LpgKgHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LPG_KG_HR");

                    b.Property<double?>("LpgRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LPG_RH");

                    b.Property<double?>("LpgTkLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LPG_TK_LTR");

                    b.Property<double?>("Maintenance")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MAINTENANCE");

                    b.Property<double?>("NgConM")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CON_M");

                    b.Property<double?>("NgMHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_M_HR");

                    b.Property<double?>("NgRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_RH");

                    b.Property<double?>("NgTkM")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_TK_M");

                    b.Property<double?>("OtherConsumable")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("OTHER_CONSUMABLE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("ServiceCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SERVICE_CHARGE");

                    b.Property<double?>("StaemGenKg")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("STAEM_GEN_KG");

                    b.Property<double?>("SteamKgHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("STEAM_KG_HR");

                    b.Property<double?>("TkKgSteamGenCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_KG_STEAM_GEN_COST");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL");

                    b.Property<double?>("TotalRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_RH");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<double?>("Troubleshooting")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TROUBLESHOOTING");

                    b.Property<double?>("WaterInletLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("WATER_INLET_LTR");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_BOILER_READING_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBoilerRmsRoom", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("NgConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION");

                    b.Property<double?>("NgConsumptionHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION_HR");

                    b.Property<double?>("NgTk")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_TK");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("TkHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_HR");

                    b.Property<double?>("ToalRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOAL_RH");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_BOILER_RMS_ROOM", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBrandInfo", b =>
                {
                    b.Property<int>("Brndid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BRNDID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Brndid"));

                    b.Property<string>("BrndName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BRND_NAME");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Brndid");

                    b.ToTable("TBL_BRAND_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBuildingInfo", b =>
                {
                    b.Property<int>("Bldid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BLDID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Bldid"));

                    b.Property<string>("BldName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BLD_NAME");

                    b.Property<int?>("Comid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("COMID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .HasColumnName("REMARKS")
                        .IsFixedLength();

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Bldid");

                    b.HasIndex("Comid");

                    b.ToTable("TBL_BUILDING_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblCngRate", b =>
                {
                    b.Property<int>("Cngrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CNGRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cngrid"));

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("TrDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UOM");

                    b.HasKey("Cngrid");

                    b.ToTable("TBL_CNG_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblCompanyInfo", b =>
                {
                    b.Property<int>("Comid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("COMID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Comid"));

                    b.Property<string>("ComAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("COM_ADDRESS");

                    b.Property<string>("ComContact")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COM_CONTACT");

                    b.Property<string>("ComEmail")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COM_EMAIL");

                    b.Property<string>("ComName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("COM_NAME");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Comid");

                    b.ToTable("TBL_COMPANY_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblCountryInfo", b =>
                {
                    b.Property<int>("Cntid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CNTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Cntid"));

                    b.Property<string>("CntCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CNT_CODE");

                    b.Property<string>("CntName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CNT_NAME");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Cntid");

                    b.ToTable("TBL_COUNTRY_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblDieselRate", b =>
                {
                    b.Property<int>("Drid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Drid"));

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("TrDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UOM");

                    b.HasKey("Drid");

                    b.ToTable("TBL_DIESEL_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblDiselGeneratorReadingInfo", b =>
                {
                    b.Property<int>("Trid")
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    b.Property<double?>("Chemical")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CHEMICAL");

                    b.Property<double?>("DieselConsumptionHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DIESEL_CONSUMPTION_HR");

                    b.Property<double?>("DieselConsumptionKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DIESEL_CONSUMPTION_KWH");

                    b.Property<double?>("DieselConsumptionLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DIESEL_CONSUMPTION_LTR");

                    b.Property<double?>("DieselTkLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DIESEL_TK_LTR");

                    b.Property<double?>("ElectricityGenerationKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("ELECTRICITY_GENERATION_KWH");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("LubOilConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LUB_OIL_CONSUMPTION");

                    b.Property<double?>("LubOilTkLtr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LUB_OIL_TK_LTR");

                    b.Property<double?>("OthersConsumable")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("OTHERS_CONSUMABLE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("RepairCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("REPAIR_CHARGE");

                    b.Property<double?>("RunningHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RUNNING_HR");

                    b.Property<double?>("ServiceCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SERVICE_CHARGE");

                    b.Property<double?>("TkKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_KWH");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<double?>("Troubleshooting")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TROUBLESHOOTING");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_DISEL_GENERATOR_READING_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblEquipmentDetail", b =>
                {
                    b.Property<int>("Eqid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Eqid"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("BRAND");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CAPACITY");

                    b.Property<string>("CurrentLocation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CURRENT_LOCATION");

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EQUIPMENT_NAME");

                    b.Property<DateTime?>("InstallDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("INSTALL_DATE");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODEL");

                    b.Property<string>("Slno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SLNO");

                    b.HasKey("Eqid");

                    b.ToTable("TBL_EQUIPMENT_DETAILS", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblEtpPlanCostInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<double?>("AntifoamConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("ANTIFOAM_CONSUMPTION");

                    b.Property<double?>("AntifoamCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("ANTIFOAM_COST");

                    b.Property<double?>("BiocleanConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("BIOCLEAN_CONSUMPTION");

                    b.Property<double?>("BiocleanCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("BIOCLEAN_COST");

                    b.Property<double?>("ChemicalCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CHEMICAL_COST");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<double?>("DailyEffluentFlow")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DAILY_EFFLUENT_FLOW");

                    b.Property<double?>("DailyEtpCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DAILY_ETP_COST");

                    b.Property<double?>("DapConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DAP_CONSUMPTION");

                    b.Property<double?>("DapCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DAP_COST");

                    b.Property<double?>("DecoloringConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DECOLORING_CONSUMPTION");

                    b.Property<double?>("DecoloringCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DECOLORING_COST");

                    b.Property<double?>("DyeingProduction")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DYEING_PRODUCTION");

                    b.Property<double?>("EffluentFlowThrough")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("EFFLUENT_FLOW_THROUGH");

                    b.Property<double?>("EflluentTreatmentPerKgDyeing")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("EFLLUENT_TREATMENT_PER_KG_DYEING");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("EtpChemCostPerKgDyeing")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("ETP_CHEM_COST_PER_KG_DYEING");

                    b.Property<double?>("GrandTotalCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("GRAND_TOTAL_COST");

                    b.Property<double?>("H2so4Consumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("H2SO4_CONSUMPTION");

                    b.Property<double?>("H2so4Cost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("H2SO4_COST");

                    b.Property<double?>("MaintenanceCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MAINTENANCE_COST");

                    b.Property<double?>("ManpowerSalary")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MANPOWER_SALARY");

                    b.Property<double?>("MiscellaneousCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MISCELLANEOUS_COST");

                    b.Property<double?>("MolassasesConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MOLASSASES_CONSUMPTION");

                    b.Property<double?>("MolassasesCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MOLASSASES_COST");

                    b.Property<double?>("PolymerConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("POLYMER_CONSUMPTION");

                    b.Property<double?>("PolymerCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("POLYMER_COST");

                    b.Property<double?>("TotalChemicalCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_CHEMICAL_COST");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<double?>("UreaConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("UREA_CONSUMPTION");

                    b.Property<double?>("UreaCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("UREA_COST");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_ETP_PLAN_COST_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFloorInfo", b =>
                {
                    b.Property<int>("Flid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FLID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Flid"));

                    b.Property<int?>("Bldid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("BLDID");

                    b.Property<int?>("Comid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("COMID");

                    b.Property<string>("Flname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("FLNAME");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Flid");

                    b.HasIndex("Bldid");

                    b.HasIndex("Comid");

                    b.ToTable("TBL_FLOOR_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFncItem", b =>
                {
                    b.Property<int>("Fncid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FNCID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fncid"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ITEM_NAME");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UOM");

                    b.HasKey("Fncid");

                    b.ToTable("TBL_FNC_ITEM", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFncItemRate", b =>
                {
                    b.Property<int>("Fncrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("FNCRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Fncrid"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("DATE");

                    b.Property<int?>("Fncid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("FNCID");

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.HasKey("Fncrid");

                    b.HasIndex("Fncid");

                    b.ToTable("TBL_FNC_ITEM_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblGenRmsRoom", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("NgConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION");

                    b.Property<double?>("NgConsumptionHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION_HR");

                    b.Property<double?>("NgTk")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_TK");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("TkHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_HR");

                    b.Property<double?>("ToalRh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOAL_RH");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_GEN_RMS_ROOM", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblLoadChartMasterFile", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<double?>("AmpSignalPhase")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("AMP_SIGNAL_PHASE");

                    b.Property<double?>("AmpThreePhase")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("AMP_THREE_PHASE");

                    b.Property<int?>("Bldid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("BLDID");

                    b.Property<int?>("Brndid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("BRNDID");

                    b.Property<string>("Capacity")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CAPACITY");

                    b.Property<DateTime?>("CmsnDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CMSN_DATE");

                    b.Property<int?>("Cntid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("CNTID");

                    b.Property<int?>("Comid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("COMID");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int?>("Flid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("FLID");

                    b.Property<int?>("Ltid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("LTID");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MODEL");

                    b.Property<double?>("Pf")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("PF");

                    b.Property<int?>("Qty")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("QTY");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("SlNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SL_NO");

                    b.Property<double?>("StandbyLoadKw")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("STANDBY_LOAD_KW");

                    b.Property<double?>("SubTotalKw400v")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SUB_TOTAL_KW_400V");

                    b.Property<double?>("SubTotalWatt")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SUB_TOTAL_WATT");

                    b.Property<double?>("TotalLoadWithoutStandby")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_LOAD_WITHOUT_STANDBY");

                    b.Property<DateTime?>("Trdate")
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TYPE");

                    b.Property<int?>("Volt")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("VOLT");

                    b.Property<int?>("Watt")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("WATT");

                    b.HasKey("Trid");

                    b.HasIndex("Bldid");

                    b.HasIndex("Brndid");

                    b.HasIndex("Cntid");

                    b.HasIndex("Comid");

                    b.HasIndex("Flid");

                    b.HasIndex("Ltid");

                    b.ToTable("TBL_LOAD_CHART_MASTER_FILE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblLoadTypeInfo", b =>
                {
                    b.Property<int>("Ltid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LTID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Ltid"));

                    b.Property<string>("Ltname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("LTNAME");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.HasKey("Ltid");

                    b.ToTable("TBL_LOAD_TYPE_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblLpgRate", b =>
                {
                    b.Property<int>("Lpgrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LPGRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Lpgrid"));

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("TrDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UOM");

                    b.HasKey("Lpgrid");

                    b.ToTable("TBL_LPG_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblLuboilRate", b =>
                {
                    b.Property<int>("Loid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("LOID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Loid"));

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("TrDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UOM");

                    b.HasKey("Loid");

                    b.ToTable("TBL_LUBOIL_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblMenu", b =>
                {
                    b.Property<int>("MenuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenuId"));

                    b.Property<string>("MenuName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("MenuId");

                    b.HasIndex("ModuleId");

                    b.ToTable("Menus", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblModule", b =>
                {
                    b.Property<int>("ModuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModuleId"));

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ModuleId");

                    b.ToTable("Modules", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblNaclRate", b =>
                {
                    b.Property<int>("Naclrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NACLRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Naclrid"));

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("TrDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("UOM");

                    b.HasKey("Naclrid");

                    b.ToTable("TBL_NACL_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblNgGeneratorReadingInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<double?>("ChemicalCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CHEMICAL_COST");

                    b.Property<double?>("CngConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CNG_CONSUMPTION");

                    b.Property<double?>("CngCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CNG_COST");

                    b.Property<double?>("EGeneration")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("E_GENERATION");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("KwhUnitNgConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("KWH_UNIT_NG_CONSUMPTION");

                    b.Property<double?>("LubOilConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LUB_OIL_CONSUMPTION");

                    b.Property<double?>("LubOilCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("LUB_OIL_COST");

                    b.Property<double?>("NgConsumptionHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION_HR");

                    b.Property<double?>("NgConsumptionKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION_KWH");

                    b.Property<double?>("NgConsumptionM")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_CONSUMPTION_M");

                    b.Property<double?>("NgTkM")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NG_TK_M");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("RepairCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("REPAIR_CHARGE");

                    b.Property<double?>("RunningHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RUNNING_HR");

                    b.Property<double?>("ServiceCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SERVICE_CHARGE");

                    b.Property<double?>("TkKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_KWH");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL");

                    b.Property<DateTime?>("Trdate")
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<double?>("Troubleshooting")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TROUBLESHOOTING");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_NG_GENERATOR_READING_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblNgRate", b =>
                {
                    b.Property<int>("NgrId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NGRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NgrId"));

                    b.Property<double?>("Rate")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RATE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("STATUS");

                    b.Property<DateTime?>("TrDate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<string>("Uom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UOM");

                    b.HasKey("NgrId");

                    b.ToTable("TBL_NG_RATE", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblPermissionAction", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ActionId");

                    b.ToTable("PermissionActions", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblRebReadingInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<double?>("BdtKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("BDT_KWH");

                    b.Property<double?>("ElecGen")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("ELEC_GEN");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("OtConsumable")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("OT_CONSUMABLE");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("RepairCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("REPAIR_CHARGE");

                    b.Property<double?>("RunHr")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("RUN_HR");

                    b.Property<double?>("ServiceCharge")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SERVICE_CHARGE");

                    b.Property<double?>("TkKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_KWH");

                    b.Property<double?>("Total")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL");

                    b.Property<DateTime?>("Trdate")
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<double?>("Troubleshoot")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TROUBLESHOOT");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_REB_READING_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblSolarReadingInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("GenerationKwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("GENERATION_KWH");

                    b.Property<double?>("PerUnitGenCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("PER_UNIT_GEN_COST");

                    b.Property<string>("Remarks")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("ServiceChargeCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SERVICE_CHARGE_COST");

                    b.Property<double?>("SparePartsCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SPARE_PARTS_COST");

                    b.Property<double?>("TotalCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_COST");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_SOLAR_READING_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblUserPermission", b =>
                {
                    b.Property<int>("UserPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserPermissionId"));

                    b.Property<int>("ActionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAllowed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MenuId")
                        .HasColumnType("int");

                    b.Property<int>("ModuleId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserPermissionId")
                        .HasName("PK_UserPermissions");

                    b.HasIndex("ActionId");

                    b.HasIndex("MenuId");

                    b.HasIndex("ModuleId");

                    b.ToTable("UserPermissions", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblWtpPlanCostInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<double?>("DeepPump1")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DEEP_PUMP_1");

                    b.Property<double?>("DeepPump2")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DEEP_PUMP_2");

                    b.Property<double?>("DeepPump3")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DEEP_PUMP_3");

                    b.Property<double?>("DeepPump4")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("DEEP_PUMP_4");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("Kwh")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("KWH");

                    b.Property<double?>("Maintenance")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("MAINTENANCE");

                    b.Property<double?>("NaclConsumption")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NACL_CONSUMPTION");

                    b.Property<double?>("NaclCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("NACL_COST");

                    b.Property<double?>("Opt01")
                        .HasColumnType("float")
                        .HasColumnName("OPT01");

                    b.Property<double?>("Opt2")
                        .HasColumnType("float")
                        .HasColumnName("OPT2");

                    b.Property<double?>("Opt3")
                        .HasColumnType("float")
                        .HasColumnName("OPT3");

                    b.Property<double?>("Remarks")
                        .HasColumnType("float")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("Softner1")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SOFTNER_1");

                    b.Property<double?>("Softner2")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SOFTNER_2");

                    b.Property<double?>("Softner3")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SOFTNER_3");

                    b.Property<double?>("Softner4")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SOFTNER_4");

                    b.Property<double?>("SoftnerGeneration")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SOFTNER_GENERATION");

                    b.Property<double?>("TkMcSoftWater")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TK_MC_SOFT_WATER");

                    b.Property<double?>("TotalCost")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_COST");

                    b.Property<double?>("TotalDrawing")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_DRAWING");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UPDATED_BY");

                    b.HasKey("Trid")
                        .HasName("PK_TBL_WTP_PLAN_COST");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_WTP_PLAN_COST_INFO", (string)null);
                });

            modelBuilder.Entity("UtilityManagement.Models.TblWtpWaterConsumptionInfo", b =>
                {
                    b.Property<int>("Trid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TRID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Trid"));

                    b.Property<double?>("BackWashWater")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("BACK_WASH_WATER");

                    b.Property<double?>("ConDyeingHotWaterIn")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CON_DYEING_HOT_WATER_IN");

                    b.Property<double?>("ConDyeingHotWaterOut")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CON_DYEING_HOT_WATER_OUT");

                    b.Property<double?>("ConsumptionB1")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_B1");

                    b.Property<double?>("ConsumptionB11")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_B11");

                    b.Property<double?>("ConsumptionB12")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_B12");

                    b.Property<double?>("ConsumptionB7")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_B7");

                    b.Property<double?>("ConsumptionChiller")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_CHILLER");

                    b.Property<double?>("ConsumptionConstruction")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_CONSTRUCTION");

                    b.Property<double?>("ConsumptionD1")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_D1");

                    b.Property<double?>("ConsumptionD2")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_D2");

                    b.Property<double?>("ConsumptionFinishing")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_FINISHING");

                    b.Property<double?>("ConsumptionGenerator")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_GENERATOR");

                    b.Property<double?>("ConsumptionSlitting")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_SLITTING");

                    b.Property<double?>("ConsumptionSteam")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("CONSUMPTION_STEAM");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CREATED_BY");

                    b.Property<int?>("Eqid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("EQID");

                    b.Property<double?>("Opt01")
                        .HasColumnType("float")
                        .HasColumnName("OPT01");

                    b.Property<double?>("Opt03")
                        .HasColumnType("float")
                        .HasColumnName("OPT03");

                    b.Property<double?>("Opto2")
                        .HasColumnType("float")
                        .HasColumnName("OPTO2");

                    b.Property<string>("Remarks")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("REMARKS");

                    b.Property<double?>("SurplusRawWater")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("SURPLUS_RAW_WATER");

                    b.Property<double?>("TotalConsumptionRawWater")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_CONSUMPTION_RAW_WATER");

                    b.Property<double?>("TotalConsumptionSoftWater")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("TOTAL_CONSUMPTION_SOFT_WATER");

                    b.Property<DateTime?>("Trdate")
                        .IsRequired()
                        .HasColumnType("datetime")
                        .HasColumnName("TRDATE");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_AT");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<double?>("Washing")
                        .IsRequired()
                        .HasColumnType("float")
                        .HasColumnName("WASHING");

                    b.HasKey("Trid");

                    b.HasIndex("Eqid");

                    b.ToTable("TBL_WTP_WATER_CONSUMPTION_INFO", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("UtilityManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("UtilityManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UtilityManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("UtilityManagement.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBoilerReadingInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblBoilerReadingInfo")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_BOILER_READING_INFO_TBL_BOILER_READING_INFO");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBoilerRmsRoom", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblBoilerRmsRooms")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_BOILER_RMS_ROOM_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBuildingInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblCompanyInfo", "Com")
                        .WithMany("TblBuildingInfo")
                        .HasForeignKey("Comid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_BUILDING_INFO_TBL_BUILDING_INFO");

                    b.Navigation("Com");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblDiselGeneratorReadingInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblDiselGeneratorReadingInfos")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_DISEL_GENERATOR_READING_INFO_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblEtpPlanCostInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblEtpPlanCostInfo")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_ETP_PLAN_COST_TBL_ETP_PLAN_COST_INFO");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFloorInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblBuildingInfo", "Building")
                        .WithMany("TblFloorInfo")
                        .HasForeignKey("Bldid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_FLOOR_INFO_TBL_BUILDING_INFO");

                    b.HasOne("UtilityManagement.Models.TblCompanyInfo", "Company")
                        .WithMany("TblFloorInfo")
                        .HasForeignKey("Comid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_FLOOR_INFO_TBL_COMPANY_INFO");

                    b.Navigation("Building");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFncItemRate", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblFncItem", "Fnc")
                        .WithMany("TblFncItemRates")
                        .HasForeignKey("Fncid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_FNC_ITEM_RATE_TBL_FNC_ITEM");

                    b.Navigation("Fnc");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblGenRmsRoom", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblGenRmsRooms")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_GEN_RMS_ROOM_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblLoadChartMasterFile", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblBuildingInfo", "Building")
                        .WithMany("TblLoadChartMasterFiles")
                        .HasForeignKey("Bldid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_LOAD_CHART_MASTER_FILE_TBL_BUILDING_INFO");

                    b.HasOne("UtilityManagement.Models.TblBrandInfo", "Brnd")
                        .WithMany("TblLoadChartMasterFiles")
                        .HasForeignKey("Brndid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_LOAD_CHART_MASTER_FILE_TBL_BRAND_INFO");

                    b.HasOne("UtilityManagement.Models.TblCountryInfo", "Cnt")
                        .WithMany("TblLoadChartMasterFiles")
                        .HasForeignKey("Cntid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_LOAD_CHART_MASTER_FILE_TBL_COUNTRY_INFO");

                    b.HasOne("UtilityManagement.Models.TblCompanyInfo", "Company")
                        .WithMany("TblLoadChartMasterFiles")
                        .HasForeignKey("Comid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_LOAD_CHART_MASTER_FILE_TBL_COMPANY_INFO");

                    b.HasOne("UtilityManagement.Models.TblFloorInfo", "Fl")
                        .WithMany("TblLoadChartMasterFiles")
                        .HasForeignKey("Flid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_LOAD_CHART_MASTER_FILE_TBL_FLOOR_INFO");

                    b.HasOne("UtilityManagement.Models.TblLoadTypeInfo", "Lt")
                        .WithMany("TblLoadChartMasterFiles")
                        .HasForeignKey("Ltid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_LOAD_CHART_MASTER_FILE_TBL_LOAD_TYPE_INFO");

                    b.Navigation("Brnd");

                    b.Navigation("Building");

                    b.Navigation("Cnt");

                    b.Navigation("Company");

                    b.Navigation("Fl");

                    b.Navigation("Lt");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblMenu", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblModule", null)
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UtilityManagement.Models.TblNgGeneratorReadingInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblNgGeneratorReadingInfos")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_NG_GENERATOR_READING_INFO_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblRebReadingInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblRebReadingInfos")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_REB_READING_INFO_TBL_REB_READING_INFO");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblSolarReadingInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblSolarReadingInfos")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_SOLAR_READING_INFO_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblUserPermission", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblPermissionAction", "Action")
                        .WithMany()
                        .HasForeignKey("ActionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityManagement.Models.TblMenu", "Menu")
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("UtilityManagement.Models.TblModule", "Module")
                        .WithMany()
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Action");

                    b.Navigation("Menu");

                    b.Navigation("Module");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblWtpPlanCostInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblWtpPlanCostInfos")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_WTP_PLAN_COST_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblWtpWaterConsumptionInfo", b =>
                {
                    b.HasOne("UtilityManagement.Models.TblEquipmentDetail", "Eq")
                        .WithMany("TblWtpWaterConsumptionInfos")
                        .HasForeignKey("Eqid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TBL_WTP_WATER_CONSUMPTION_INFO_TBL_EQUIPMENT_DETAILS");

                    b.Navigation("Eq");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBrandInfo", b =>
                {
                    b.Navigation("TblLoadChartMasterFiles");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblBuildingInfo", b =>
                {
                    b.Navigation("TblFloorInfo");

                    b.Navigation("TblLoadChartMasterFiles");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblCompanyInfo", b =>
                {
                    b.Navigation("TblBuildingInfo");

                    b.Navigation("TblFloorInfo");

                    b.Navigation("TblLoadChartMasterFiles");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblCountryInfo", b =>
                {
                    b.Navigation("TblLoadChartMasterFiles");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblEquipmentDetail", b =>
                {
                    b.Navigation("TblBoilerReadingInfo");

                    b.Navigation("TblBoilerRmsRooms");

                    b.Navigation("TblDiselGeneratorReadingInfos");

                    b.Navigation("TblEtpPlanCostInfo");

                    b.Navigation("TblGenRmsRooms");

                    b.Navigation("TblNgGeneratorReadingInfos");

                    b.Navigation("TblRebReadingInfos");

                    b.Navigation("TblSolarReadingInfos");

                    b.Navigation("TblWtpPlanCostInfos");

                    b.Navigation("TblWtpWaterConsumptionInfos");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFloorInfo", b =>
                {
                    b.Navigation("TblLoadChartMasterFiles");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblFncItem", b =>
                {
                    b.Navigation("TblFncItemRates");
                });

            modelBuilder.Entity("UtilityManagement.Models.TblLoadTypeInfo", b =>
                {
                    b.Navigation("TblLoadChartMasterFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
